simulacovid:
    columns: [
        "city_id",
        "city_name",
        "state_id",
        "state_name",
        "population",
        "health_system_region",
        "last_updated_number_beds",
        "author_number_beds",
        "number_beds",
        "last_updated_number_ventilators",
        "author_number_ventilators",
        "number_ventilators",
        "confirmed_cases",
        "active_cases",
        "deaths",
        "notification_rate",
        "state_notification_rate"
    ]   
    state_agg: {
            "population": sum,
            "confirmed_cases": sum,
            "active_cases": sum,
            "deaths": sum,
            "state_notification_rate": max,
            "number_beds": sum,
            "number_ventilators": sum
    }
    
resources:
    available_proportion: 0.5
        
rules:
    rt_classification:
        column_name: 'rt_10days_ago_most_likely'
        cuts: [0, 1, 1.2, 5.001]
        categories: ['bom', 'insatisfatorio', 'ruim'] # [1, 0, -1]

    rt_growth:
        column_name: "rt_ratio_week_avg"
        cuts: [0, 0.9, 1.1, 1000]
        categories: ['melhorando', 'estabilizando', 'piorando'] # [1, 0, -1]

    dday_classification:
        column_name: 'dday_beds_best'
        cuts: [0, 30, 60, 91.001]
        categories: ['ruim', 'insatisfatorio', 'bom'] # [-1, 0, 1]

    subnotification_classification:
        column_name: 'subnotification_rate'
        cuts: [-1, 0.5, 0.7, 1.001]
        categories: ['bom', 'insatisfatorio', 'ruim']  # [1, 0, -1]

    inloco_growth:
        column_name: 'inloco_ratio_week_avgs'
        cuts: [0, 0.9, 1.1, 1000]
        categories: ['piorando', 'estabilizando', 'melhorando'] # [-1, 0, 1]
        
alerts:
    alto: 
        conditions: {
            rt_classification: "ruim",
            rt_growth: "piorando",
            dday_classification: "ruim",
            subnotification_classification: "ruim"
           }
        how: "any"
    medio: 
        conditions: {
            rt_classification: "insatisfatorio",
            rt_growth: "melhorando|estabilizando",
            dday_classification: "bom|insatisfatorio",
            subnotification_classification: "bom|insatisfatorio"  
        }
        how: "all"
    medio2: 
        conditions: {
            rt_classification: "bom|insatisfatorio",
            rt_growth: "melhorando|estabilizando",
            dday_classification: "bom|insatisfatorio",
            subnotification_classification: "insatisfatorio"  
        }
        how: "all"
    baixo:
        conditions: {
            rt_classification: "bom",
            rt_growth: "melhorando|estabilizando",
            dday_classification: "bom|insatisfatorio",
            subnotification_classification: "bom"            
        }
        how: "all"

